In [1]:
import numpy as np

**Checking if a 3 by 3 matrix is singualr or not using Numpy**

In [7]:
A = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 1, 0]])

# Compute the determinant
det = np.linalg.det(A)

print(det)


if  det == 0: 
    print(f"The Matrix {A} \n is Singular")
else:
    print(f"The Matrix {A} \n is not Singular")
    


0.0
The Matrix [[1 0 0]
 [0 1 0]
 [0 1 0]] 
 is Singular


**Solving a linear system equation with Numpy.
Let us say we have the follwoung equations:**

2a+5b =46

8a +b=32

First we need to convert them to a numpy array and then use numpy

In [1]:
import numpy as np

#Turn into a mtrix
A = np.array([[2, 5],
              [8, 1]])

# Turn constants into a matrix
B = np.array([46, 32])

# Solve the system of linear equations
solution = np.linalg.solve(A, B)

# Get the value of A and B 
a = solution[0]
b = solution[1]

# Print the values
print("a =", a)
print("b =", b)


a = 3.0
b = 8.0


**Finding the rank of a Matrix using Numpy..**

Ranks means how many info can a system of equations have..e.g you can mturn an image to a matrix then reduce rank which will in turn reduce the number of Pixels the image has 

In [3]:

mat = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Find the rank of the matrix
rank2 = np.linalg.matrix_rank(mat)

print("Rank:", rank2)


Rank: 2


**Finding the distance 2 vectors**

In [3]:
v1 = np.array([1,5])
v2 = np.array([6,2])
dis = np.linalg.norm(v1-v2)
print(f"The distance berween 2 vectors is : {dis}")

The distance berween 2 vectors is : 5.830951894845301


**Multiplying vectors by a scalar**

In [8]:
vec = np.array([1,2])
scalar = vec[0] + vec[1]
print(scalar)
res = scalar * vec

ResV= res*vec[0], res*vec[1]
print(ResV)

3
(array([3, 6]), array([ 6, 12]))


**Finding The Droduct**

In [10]:
fruit = np.array([2,5,7])
price = np.array([4,7,8])
dot_pro = np.dot(fruit, price)
print(f"The total price is {dot_pro}")

The total price is 99


**Finding the inverse of a mtrix with numpy..**

Singular ONES HAS NO INVERSE

In [2]:
# matrix
matrix = np.array([[3, 1], [1, 2]])

# Calculate the inverse
inverse_matrix = np.linalg.inv(matrix)

print("Original matrix:\n", matrix)
print("Inverse matrix:\n", inverse_matrix)


Original matrix:
 [[3 1]
 [1 2]]
Inverse matrix:
 [[ 0.4 -0.2]
 [-0.2  0.6]]


**Finding EigenValues and Vectors with Numpy**


For example if u want to know if a 2 places have a direcet route..or how many direct routes for a big system

In [2]:


# Adjacency matrix
adjacency_matrix = np.array([[0, 1, 1, 0],
                             [1, 0, 0, 1],
                             [1, 0, 0, 1],
                             [0, 1, 1, 0]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(adjacency_matrix)

# Print eigenvalues and eigenvectors
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[-2.00000000e+00  6.59737022e-17  2.00000000e+00  0.00000000e+00]

Eigenvectors:
[[ 5.00000000e-01 -7.07106781e-01  5.00000000e-01  0.00000000e+00]
 [-5.00000000e-01 -4.63633825e-17  5.00000000e-01 -7.07106781e-01]
 [-5.00000000e-01 -3.76905605e-17  5.00000000e-01  7.07106781e-01]
 [ 5.00000000e-01  7.07106781e-01  5.00000000e-01  0.00000000e+00]]
